# Generated by Django 4.0.3 on 2023-02-03 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 16, 45, 4, 635930, tzinfo=utc)),
        ),
    ]
